version: '3.9'

services:
  nimble-miner:
    stdin_open: true
    tty: true
    build: .
    environment:
      - NVIDIA_VISIBLE_DEVICES=${GPU:-all}
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped